/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Framework */

#ifndef _Included_jni_Framework
#define _Included_jni_Framework
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Framework
 * Method:    renderGraph
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jni_Framework_renderGraph
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
